const BAD_REQUEST_STATUS = 400;
const UNATHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND_STATUS = 404;
const CONFLICT = 409;
const SERVER_ERROR_STATUS = 500;
const REQUEST_SUCCESS = 200;
const REQUEST_CREATED = 201;

module.exports = {
  BAD_REQUEST_STATUS,
  NOT_FOUND_STATUS,
  SERVER_ERROR_STATUS,
  REQUEST_CREATED,
  REQUEST_SUCCESS,
  UNATHORIZED,
  FORBIDDEN,
  CONFLICT,
};
